apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: webserver
  namespace: argocd
spec:
  project: argocd-helm
  source:
    repoURL: https://github.com/GodfredAsa/webserver.git
    targetRevision: HEAD
    path: webserver
  destination:
    server: https://kubernetes.default.svc
    namespace: webserver